### ISSUE TITLE
where we download roundabout.mp4

### ISSUE THREAD

**Issue by fariz** [earthat/ROI-marking-for-traffic-surveillance-#1]
please give us link

**Comment by earthat** [comment]
get it from [here ](https://drive.google.com/open?id=1XbG76LyEvemTTRBwQeNe9z9ZEeZVcJvY)

**Comment by fariz** [comment]
dear eathart would you like to help me count this video
and counting chicken
https://youtu.be/J-3vPRb8VGA

if it possible how can we process it ditectly from streaming via online camera
really need your help please

**Comment by earthat** [comment]
The chicken counting from this video is quite straight. You can opt many options for this but the most robust solution can be using machine learning. You should manually cut the few chicken images to get the training data and then just use any machine learning solution to detect the chicken and just make a counter on the basis of that.

Another easy solution for this video only is to mark a chicken manually and calculate the width and height of the bounding box for a chicken. Consider all chickens will be in the similar bounding box. Just make a reference line and bounding box crossing that line will increment the counter.
